udpcast-20080914
v20080914
       * Added distclean target to make Debian build easier
       * Adapted to new name of mingw compiler, and other Mingw adaptations
       * Removed obsolete m486 flag
       * Fixed parameter types for getsockopt
       * If there are no participants after autostart delay, do not
       transmit but exit right away
       * RpmLint fixes
       * Adapt to Solaris 9 sparc
       * Added a lot of short opts (for systems without getopt_long)
       * pluggable rate governor
       * Mingw fixes (socket closing)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3551,6 +3551,78 @@ _ACEOF
 fi
 
 
+{ echo "$as_me:$LINENO: checking for dlsym in -ldl" >&5
+echo $ECHO_N "checking for dlsym in -ldl... $ECHO_C" >&6; }
+if test "${ac_cv_lib_dl_dlsym+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ldl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char dlsym ();
+int
+main ()
+{
+return dlsym ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_dl_dlsym=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_dl_dlsym=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_dl_dlsym" >&5
+echo "${ECHO_T}$ac_cv_lib_dl_dlsym" >&6; }
+if test $ac_cv_lib_dl_dlsym = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBDL 1
+_ACEOF
+
+  LIBS="-ldl $LIBS"
+
+fi
+
+
+
 { echo "$as_me:$LINENO: checking for ANSI C header files" >&5
 echo $ECHO_N "checking for ANSI C header files... $ECHO_C" >&6; }
 if test "${ac_cv_header_stdc+set}" = set; then
@@ -3878,9 +3950,12 @@ done
 
 
 
+
+
+
 for ac_header in fcntl.h limits.h sys/ioctl.h sys/time.h arpa/inet.h netdb.h \
 sys/select.h sys/sockio.h sys/socket.h sys/param.h memory.h malloc.h signal.h \
-net/if.h netinet/in.h winsock2.h sys/uio.h
+net/if.h netinet/in.h winsock2.h sys/uio.h getopt.h dlfcn.h string.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -4978,7 +5053,9 @@ _ACEOF
 
 
 
-for ac_func in atexit on_exit tcsetattr lseek64 snprintf inet_pton inet_aton
+
+
+for ac_func in atexit on_exit tcsetattr lseek64 snprintf inet_pton inet_aton getopt_long dlsym
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -5344,9 +5421,6 @@ fi
 my_host_os=`echo $host_os1 $host_os2 $host_os3 | sort -u`
 objs=`echo $srcdir/*.c | sed 's/\.c$/.o/' `
 if [ "X$GCC" = "Xyes" ] ; then
-    if [ "$host_cpu" = i486 ] ; then
-	    CFLAGS="$CFLAGS -m486"
-    fi
     Wall=-Wall
     if [ "$host_os3" = sunos ] ; then
 	    Wall=""
@@ -5354,6 +5428,7 @@ if [ "X$GCC" = "Xyes" ] ; then
     if [ "$host_os3" = solaris ] ; then
 	    CFLAGS="$CFLAGS -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED=1 -D__EXTENSIONS__"
  	    LIBS="$LIBS -lnsl -lsocket"
+	    Wall=""
     fi
     if [ "$host_os3" = ultrix ] ; then
 	    Wall=""
@@ -5408,7 +5483,7 @@ if [ $host_os3 = nextstep ] ; then
     SHLIB=""
 fi
 
-if [ $host_os3 = mingw ] ; then
+if [ $host_os3 = mingw -o $host_os3 = mingw32msvc ] ; then
     LIBS="$LIBS -lws2_32 -liphlpapi"
     EXESUFFIX=".exe"
 fi
@@ -5416,6 +5491,9 @@ fi
 if [ -d /usr/5lib ] ; then
 	extralibdir=-L/usr/5lib
 fi
+
+
+
 
 
 
